import type { Metadata } from "next";
import { Questrial,Rubik } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import NavbarWrapper from "@/components/NavbarWrapper";
import { Providers } from "@/providers/Providers";
import ModalManager from "@/components/ModalManager";
import { Toaster } from "sonner";


const questrial = Questrial({
  variable: "--font-questrial", 
  subsets: ["latin"],
  weight: ["400"],
});

const rubik = Rubik({
  variable: "--font-rubik",
  subsets: ["latin"],
  weight: ["400", "500", "700"], 
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={questrial.variable}>
      <body
        className={`${rubik.variable} antialiased`}
      >
        <Providers>
              <NavbarWrapper/>
              {/*  */}
               <ModalManager />
              {/* main */}
                <main className="min-h-screen">{children}</main>
                {/* for toast */}
                <Toaster />
              {/* footer */}
              <Footer/>
        </Providers>
      </body>
    </html>
  );
}
